import importlib.machinery
import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from ptlib import project, vendoring  # noqa: E402

loader = importlib.machinery.SourceFileLoader("vendor_cli", str(ROOT / "scripts" / "vendor"))
spec = importlib.util.spec_from_loader("vendor_cli", loader)
vendor = importlib.util.module_from_spec(spec)
loader.exec_module(vendor)


class PlanTest(unittest.TestCase):
    def test_maps_roles_skills_and_support_files(self):
        plan = vendoring.plan(ROOT)
        self.assertIn(".claude/agents/qa.md", plan)
        self.assertIn(".claude/skills/slot-pm/SKILL.md", plan)
        self.assertIn(".claude/product-team/scripts/backlog", plan)
        self.assertIn(".claude/product-team/reference/workflow.md", plan)
        self.assertIn(".claude/product-team/.claude-plugin/plugin.json", plan)
        self.assertFalse(any("__pycache__" in rel or rel.startswith(".claude/product-team/tests") for rel in plan))


class RewriteTest(unittest.TestCase):
    def test_paths_and_skill_names_point_at_the_copy(self):
        text = "---\nname: x\n---\nRun `${CLAUDE_PLUGIN_ROOT}/scripts/backlog` then `/product-team:slot-qa`.\n"
        out = vendoring.rewrite(text, ".claude/skills/x/SKILL.md", "0.3.0")
        self.assertIn("`.claude/product-team/scripts/backlog`", out)
        self.assertIn("`/slot-qa`", out)
        self.assertTrue(out.startswith("---\nname: x\n---\n<!-- Generated by the product-team plugin (0.3.0)"))

    def test_frontmatter_stays_first(self):
        out = vendoring.rewrite("---\nname: qa\nmodel: m\n---\nbody", ".claude/agents/qa.md", "1")
        self.assertEqual(out.split("\n")[:4], ["---", "name: qa", "model: m", "---"])


class InstallTest(unittest.TestCase):
    def test_install_update_and_ownership(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            (target / ".claude/agents").mkdir(parents=True)
            (target / ".claude/agents/qa.md").write_text("the project's own qa agent")
            with self.assertRaises(vendor.Conflict) as caught:
                vendor.install(ROOT, target)  # never overwrite what the plugin did not write
            self.assertEqual(caught.exception.paths, [".claude/agents/qa.md"])

            (target / ".claude/agents/qa.md").unlink()
            first = vendor.install(ROOT, target)
            self.assertTrue(first["written"])
            manifest = json.loads((target / vendoring.MANIFEST).read_text())
            self.assertIn(".claude/agents/qa.md", manifest["files"])

            (target / ".claude/agents/pm.md").write_text("edited by hand")
            stale = target / ".claude/skills/retired/SKILL.md"
            stale.parent.mkdir(parents=True)
            stale.write_text("old")
            manifest["files"][".claude/skills/retired/SKILL.md"] = vendoring.sha(stale)
            vendoring.write_manifest(target, manifest)

            second = vendor.install(ROOT, target)
            self.assertEqual(second["overwrote_local_edits"], [".claude/agents/pm.md"])
            self.assertEqual(second["removed"], [".claude/skills/retired/SKILL.md"])
            self.assertNotIn("edited by hand", (target / ".claude/agents/pm.md").read_text())

            third = vendor.install(ROOT, target)
            self.assertEqual(third["written"], [])  # idempotent


class VendoredCopyTest(unittest.TestCase):
    def test_installing_from_the_vendored_copy_is_refused(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            vendor.install(ROOT, target)
            with self.assertRaises(SystemExit):
                vendor.install(target / vendoring.HOME, target)
            self.assertTrue((target / ".claude/agents/qa.md").exists())


class SelfUpdateVerificationTest(unittest.TestCase):
    def test_installed_manifest_is_exactly_what_verification_expects(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = vendor.install(ROOT, target)
            files = vendoring.render(ROOT, result["version"]["version"])
            expected = vendoring.manifest_bytes(result["version"]["version"], result["version"]["commit"], files)
            self.assertEqual((target / vendoring.MANIFEST).read_bytes(), expected)
            for rel, data in files.items():
                self.assertEqual((target / rel).read_bytes(), data, rel)

    def test_only_generated_files_may_change(self):
        allowed = {".claude/agents/qa.md"}
        changes = [{"filename": ".claude/agents/qa.md", "status": "modified"},
                   {"filename": vendoring.MANIFEST, "status": "modified"},
                   {"filename": ".claude/settings.json", "status": "modified"},
                   {"filename": ".claude/agents/evil.md", "status": "added"},
                   {"filename": ".product-team/project.yml", "status": "modified"}]
        problems = vendoring.self_update_violations(changes, allowed)
        self.assertEqual(len(problems), 3)
        self.assertTrue(any("settings" in p for p in problems))

    def test_settings_are_refused_even_if_listed(self):
        problems = vendoring.self_update_violations([{"filename": ".claude/settings.local.json", "status": "added"}],
                                                    {".claude/settings.local.json"})
        self.assertEqual(len(problems), 1)


class PluginRefTest(unittest.TestCase):
    def test_reviewer_logins_inline_and_block_lists(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "project.yml"
            cases = {
                "team:\n  reviewer_logins: []\n": [],
                "team:\n  reviewer_logins: [bot-a, 'bot-b']\n": ["bot-a", "bot-b"],
                "team:\n  reviewer_logins:\n    - bot-a\n    - \"bot-b\"  # note\n  plugin_ref: stable\n": ["bot-a", "bot-b"],
                "team:\n  reviewer_logins:\n\n    - bot-a\nowner:\n  timezone: x\n": ["bot-a"],
            }
            for text, expected in cases.items():
                with self.subTest(text=text):
                    path.write_text(text)
                    self.assertEqual(project.reviewer_logins(str(path)), expected)

    def test_defaults_to_stable_and_reads_a_pin(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "project.yml"
            self.assertEqual(project.plugin_ref(str(path)), "stable")
            path.write_text("team:\n  plugin_ref: v0.3.0\n")
            self.assertEqual(project.plugin_ref(str(path)), "v0.3.0")


if __name__ == "__main__":
    unittest.main()
