"""What `vendor` copies into a product repository and how, kept pure enough to test."""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Dict, List, Tuple

PLUGIN_REPO = "https://github.com/geeera/product-team-plugin"
HOME = ".claude/product-team"
MANIFEST = f"{HOME}/MANIFEST.json"
NOTICE = ("<!-- Generated by the product-team plugin ({version}). Do not edit here: change it in "
          "https://github.com/geeera/product-team-plugin and let self-update bring it in. -->")
SKIP_PARTS = {"__pycache__", ".DS_Store"}

# source subtree -> (destination, rewrite markdown?)
TREES = (
    ("agents", ".claude/agents", True),
    ("skills", ".claude/skills", True),
    ("scripts", f"{HOME}/scripts", False),
    ("reference", f"{HOME}/reference", True),
    ("templates", f"{HOME}/templates", True),
)
FILES = ((".claude-plugin/plugin.json", f"{HOME}/.claude-plugin/plugin.json"),
         ("CHANGELOG.md", f"{HOME}/CHANGELOG.md"), ("LICENSE", f"{HOME}/LICENSE"))


def plan(src: Path) -> Dict[str, Tuple[Path, bool]]:
    out: Dict[str, Tuple[Path, bool]] = {}
    for tree, dest, rewrite_md in TREES:
        for path in sorted((src / tree).rglob("*")):
            if path.is_dir() or SKIP_PARTS & set(path.parts) or path.suffix == ".pyc":
                continue
            rel = f"{dest}/{path.relative_to(src / tree).as_posix()}"
            out[rel] = (path, rewrite_md and path.suffix == ".md")
    for source, dest in FILES:
        if (src / source).exists():
            out[dest] = (src / source, False)
    return out


def rewrite(text: str, rel: str, version: str = "") -> str:
    text = text.replace("${CLAUDE_PLUGIN_ROOT}", HOME)
    # As project skills they are /slot-pm, not /product-team:slot-pm.
    text = text.replace("/product-team:", "/")
    if rel.startswith((".claude/agents/", ".claude/skills/")) and text.startswith("---\n"):
        end = text.index("\n---", 4) + len("\n---")
        text = text[:end] + "\n" + NOTICE.format(version=version or "see MANIFEST.json") + text[end:]
    return text


def render(src: Path, version: str) -> Dict[str, bytes]:
    """Every generated file's exact bytes for this plugin checkout — what `vendor install` writes."""
    out: Dict[str, bytes] = {}
    for rel, (source, rewrite_md) in plan(src).items():
        data = source.read_bytes()
        out[rel] = rewrite(data.decode("utf-8"), rel, version).encode("utf-8") if rewrite_md else data
    return out


def manifest_bytes(version: str, commit: str, files: Dict[str, bytes]) -> bytes:
    manifest = {"version": version, "commit": commit,
                "files": {rel: hashlib.sha256(data).hexdigest() for rel, data in sorted(files.items())}}
    return (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")


# The self-update PR may touch these and nothing else; settings (hooks, permissions) never.
NEVER_VENDORED = re.compile(r"^\.claude/settings[^/]*\.json$")


def self_update_violations(changes: List[dict], allowed: set) -> List[str]:
    """changes: PR files ({filename, status}); allowed: paths the verified manifest owns (old or new)."""
    problems = []
    for change in changes:
        path = change["filename"]
        if NEVER_VENDORED.match(path):
            problems.append(f"{path}: settings are never part of a plugin update")
        elif path != MANIFEST and path not in allowed:
            problems.append(f"{path}: not a generated plugin file")
    return problems


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_manifest(target: Path) -> dict:
    path = target / MANIFEST
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return {}


def write_manifest(target: Path, manifest: dict) -> None:
    path = target / MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def conflicts(target: Path, planned: Dict[str, Tuple[Path, bool]], installed: dict) -> List[str]:
    """Existing files the plugin would overwrite but never wrote: the project's own agents or skills."""
    owned = set(installed.get("files", {}))
    return sorted(rel for rel in planned if rel not in owned and (target / rel).exists())


def local_edits(target: Path, installed: dict) -> List[str]:
    """Generated files someone changed by hand since the last install (they will be overwritten)."""
    return sorted(rel for rel, digest in installed.get("files", {}).items()
                  if (target / rel).exists() and sha(target / rel) != digest)
